# Configuration for LaBaleine

debug: no

modules:
    - baleine.exchanges.bitfinex
    - baleine.exchanges.bittrex
    - baleine.exchanges.forex

plugins:
    - name: baleine.plugins.convert.Convert
    - name: baleine.plugins.file.File
      command: [rules, regles]
      file: rules.txt
    - name: baleine.plugins.price.Price
    - name: baleine.plugins.readonly.ReadOnly
      channels: [399403543880138755]
