# Configuration for LaBaleine

debug: yes
help_path: data/help

modules:
    - baleine.exchanges.bitfinex
    - baleine.exchanges.bittrex
    - baleine.exchanges.cryptopia
    - baleine.exchanges.forex

commands:
    - name: DevTools
      commands: [baleine.plugins.dev]
      permissions:
        - name: HasRolePermission
          roles: [dev]
        - name: ChannelWhitelistPermission
          channels: [bot]
    - name: Help
      commands: [baleine.plugins.help]
    - name: Pricetools
      commands: [baleine.plugins.convert, baleine.plugins.price]

plugins:
    - name: baleine.plugins.readonly.ReadOnly
      channels: [399403543880138755]
