# Configuration for LaBaleine

debug: yes
help_path: data/help

modules:
    - baleine.exchanges.bitfinex
    - baleine.exchanges.bittrex
    - baleine.exchanges.cryptopia
    - baleine.exchanges.forex

commands:
    - name: Barrier
      commands: [baleine.plugins.barrier]
    - name: DevTools
      commands: [baleine.plugins.dev]
      permissions:
        - name: HasRolePermission
          roles: [dev]
        - name: ChannelWhitelistPermission
          channels: [bot]
    - name: Help
      commands: [baleine.plugins.help]
    - name: Pricetools
      commands: [baleine.plugins.convert, baleine.plugins.price]

plugins:
    - name: baleine.plugins.readonly.ReadOnly
      channels: [399403543880138755]

barrier:
    quizzes:
        - name: hello
          file: data/barrier/newcomers.yml
          num_questions: 8
          feedback: yes
          grant_role: Baleine novice

logging:
    version: 1
    formatters:
        verbose:
            format: '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s'
            datefmt: '%H:%M:%S'
        simple:
            format: '%(levelname)s %(message)s'
    handlers:
        file:
            level: INFO
            class: logging.FileHandler
            filename: baleine.log
            formatter: verbose
        console:
            level: DEBUG
            class: logging.StreamHandler
            formatter: verbose
    root:
        level: WARNING
        handlers: [file, console]
    loggers:
        baleine:
            level: DEBUG
            handlers: [file, console]
            propagate: no
