# Configuration for LaBaleine

debug: no
help_path: data/help

modules:
    - baleine.exchange.bitfinex
    - baleine.exchange.bittrex
    - baleine.exchange.cryptopia
    - baleine.exchange.forex

commands:
    - name: Barrier
      commands: [baleine.plugins.barrier]
    - name: DevTools
      commands: [baleine.plugins.dev]
      permissions:
        - name: HasRolePermission
          roles: [dev]
        - name: ChannelWhitelistPermission
          channels: [bot, techdev]
    - name: Help
      commands: [baleine.plugins.help]
    - name: Moderation
      commands: [baleine.plugins.moderation]
      permissions:
        - name: HasRolePermission
          roles: [Modérateur trading, Modérateur minage]
    - name: Pricetools
      commands: [baleine.plugins.convert, baleine.plugins.price]

plugins:
    - name: baleine.plugins.naming.Naming
      channel: Bot
      filters:
        - match: '.*[a-zéèàç]{3}.*'
          message: "Votre nom doit comporter au moins trois lettres latines consécutives."
      badwords: data/badwords
    - name: baleine.plugins.readonly.ReadOnly
      channels:
        - 386061346342436864        # accueil sur le server officiel
        - 405775677107994655        # general sur le serveur de test
      whitelist: [administrateur, modérateur trading, modérateur minage]

barrier:
    quizzes:
        - name: novice
          file: data/barrier/newcomers.yml
          num_questions: 8
          feedback: yes
          grant_role: Baleine novice

logging:
    version: 1
    formatters:
        verbose:
            format: '%(levelname)s [%(module)s] %(message)s'
    handlers:
        console:
            level: DEBUG
            class: logging.StreamHandler
            formatter: verbose
    root:
        level: WARNING
        handlers: [console]
    loggers:
        baleine:
            level: DEBUG
            handlers: [console]
            propagate: no
